"""Add timestamp to Todo

Revision ID: 03099a41191f
Revises: 45cc28685b5a
Create Date: 2026-03-05 11:07:50.825853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03099a41191f'
down_revision = '45cc28685b5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
