"""Models updated...

Revision ID: 959402082d70
Revises: 03099a41191f
Create Date: 2026-03-05 11:15:46.474356

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '959402082d70'
down_revision = '03099a41191f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('title',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('user_id')
        batch_op.drop_column('priority')
        batch_op.drop_column('favorite')

    # ### end Alembic commands ###
